#version 460
struct _GLF_struct_25 {
 ivec3 _f0;
 uint workgroup_id;
 mat2 _f1;
} ;

struct _GLF_struct_24 {
 mat4x3 _f0;
 ivec2 _f1;
 ivec4 _f2;
 vec3 _f3;
} ;

struct _GLF_struct_23 {
 mat3x4 _f0;
 ivec3 _f1;
} ;

struct _GLF_struct_26 {
 _GLF_struct_23 _f0;
 _GLF_struct_24 _f1;
 ivec3 _f2;
 _GLF_struct_25 _f3;
} ;

struct _GLF_struct_27 {
 mat4x2 _f0;
 uint _f1;
 _GLF_struct_26 _f2;
} ;

struct _GLF_struct_20 {
 ivec4 _f0;
 bvec2 _f1;
 uint subgroup_size;
 mat2x4 _f2;
 bvec3 _f3;
} ;

struct _GLF_struct_19 {
 vec2 _f0;
 uint _f1;
 ivec3 _f2;
 mat2x4 _f3;
 mat2 _f4;
 vec4 _f5;
} ;

struct _GLF_struct_18 {
 mat2x4 _f0;
 uvec3 _f1;
 uvec2 _f2;
 bvec4 _f3;
 mat4 _f4;
 uint _f5;
} ;

struct _GLF_struct_21 {
 _GLF_struct_18 _f0;
 _GLF_struct_19 _f1;
 _GLF_struct_20 _f2;
 bvec4 _f3;
} ;

struct _GLF_struct_22 {
 _GLF_struct_21 _f0;
} ;

struct _GLF_struct_15 {
 int _f0;
 uvec3 _f1;
 ivec2 _f2;
 uvec2 _f3;
 mat3x2 _f4;
} ;

struct _GLF_struct_14 {
 bvec3 _f0;
 uvec3 _f1;
 uvec4 _f2;
 float _f3;
 ivec3 _f4;
 ivec4 _f5;
 bvec4 _f6;
} ;

struct _GLF_struct_13 {
 ivec4 _f0;
 mat4 _f1;
 mat3x4 _f2;
 vec4 _f3;
 uvec4 _f4;
 bvec2 _f5;
 mat3 _f6;
} ;

struct _GLF_struct_16 {
 _GLF_struct_13 _f0;
 uvec3 _f1;
 mat4x2 _f2;
 _GLF_struct_14 _f3;
 float _f4;
 _GLF_struct_15 _f5;
 bvec4 _f6;
} ;

struct _GLF_struct_11 {
 vec3 _f0;
 uvec2 _f1;
 uvec2 _f2;
 uvec4 _f3;
} ;

struct _GLF_struct_10 {
 uvec4 _f0;
 uvec3 _f1;
 mat2x3 _f2;
 uvec3 _f3;
} ;

struct _GLF_struct_9 {
 bvec2 _f0;
 mat3 _f1;
} ;

struct _GLF_struct_8 {
 uvec4 _f0;
 vec3 _f1;
} ;

struct _GLF_struct_12 {
 _GLF_struct_8 _f0;
 bvec2 _f1;
 _GLF_struct_9 _f2;
 mat2x4 _f3;
 _GLF_struct_10 _f4;
 _GLF_struct_11 _f5;
 bool _f6;
} ;

struct _GLF_struct_17 {
 uvec2 _f0;
 _GLF_struct_12 _f1;
 bvec4 _f2;
 _GLF_struct_16 _f3;
 uint virtual_gid;
 bool _f4;
} ;

struct _GLF_struct_5 {
 float _f0;
 mat2x3 _f1;
 mat3x2 _f2;
 ivec3 _f3;
 bvec2 _f4;
 vec2 _f5;
} ;

struct _GLF_struct_4 {
 mat3 _f0;
 bvec2 _f1;
 mat3 _f2;
 mat4x3 _f3;
} ;

struct _GLF_struct_3 {
 mat2x4 _f0;
 vec2 _f1;
 uvec3 _f2;
} ;

struct _GLF_struct_2 {
 mat3x4 _f0;
 uvec2 _f1;
} ;

struct _GLF_struct_1 {
 uint _f0;
 mat2x3 _f1;
 float _f2;
 bool _f3;
 uvec3 _f4;
 ivec2 _f5;
 uint _f6;
} ;

struct _GLF_struct_0 {
 mat2x3 _f0;
 mat3x2 _f1;
 bvec2 _f2;
 ivec4 _f3;
 vec4 _f4;
 bvec2 _f5;
 uvec2 _f6;
} ;

struct _GLF_struct_6 {
 _GLF_struct_0 _f0;
 _GLF_struct_1 _f1;
 _GLF_struct_2 _f2;
 _GLF_struct_3 _f3;
 _GLF_struct_4 _f4;
 _GLF_struct_5 _f5;
} ;

struct _GLF_struct_7 {
 _GLF_struct_6 _f0;
 uvec2 _f1;
 float _f2;
 uint subgroup_id;
} ;

layout(set = 0, binding = 1) uniform buf1 {
 vec2 injectionSwitch;
};
#extension GL_KHR_shader_subgroup_vote : enable
#extension GL_KHR_shader_subgroup_basic : enable
#extension GL_KHR_memory_scope_semantics : enable
layout(set = 0, binding = 0) buffer Buf {
 uint buf[];
};
layout(local_size_x = 128, local_size_y = 1, local_size_z = 1) in;
void main()
{
 uvec4 GLF_merged4_0_1_16_1_1_13_2_1_6_3_1_12next_virtual_gidnum_workgroupread_1workgroup_id;
 _GLF_struct_7 _GLF_struct_replacement_7 = _GLF_struct_7(_GLF_struct_6(_GLF_struct_0(mat2x3(1.0), mat3x2(1.0), bvec2(true), ivec4(1), vec4(1.0), bvec2(true), uvec2(1u)), _GLF_struct_1(1u, mat2x3(1.0), 1.0, true, uvec3(1u), ivec2(1), 1u), _GLF_struct_2(mat3x4(1.0), uvec2(1u)), _GLF_struct_3(mat2x4(1.0), vec2(1.0), uvec3(1u)), _GLF_struct_4(mat3(1.0), bvec2(true), mat3(1.0), mat4x3(1.0)), _GLF_struct_5(1.0, mat2x3(1.0), mat3x2(1.0), ivec3(1), bvec2(true), vec2(1.0))), uvec2(1u), 1.0, gl_SubgroupID);
 _GLF_struct_22 _GLF_struct_replacement_22 = _GLF_struct_22(_GLF_struct_21(_GLF_struct_18(mat2x4(1.0), uvec3(1u), uvec2(1u), bvec4(true), mat4(1.0), 1u), _GLF_struct_19(vec2(1.0), 1u, ivec3(1), mat2x4(1.0), mat2(1.0), vec4(1.0)), _GLF_struct_20(ivec4(1), bvec2(true), gl_SubgroupSize, mat2x4(1.0), bvec3(true)), bvec4(true)));
 uint subgroup_local_id = gl_SubgroupInvocationID;
 uint num_workgroup = gl_NumWorkGroups.x;
 GLF_merged4_0_1_16_1_1_13_2_1_6_3_1_12next_virtual_gidnum_workgroupread_1workgroup_id.y = num_workgroup;
 uint workgroup_size = gl_WorkGroupSize.x;
 _GLF_struct_27 _GLF_struct_replacement_27 = _GLF_struct_27(mat4x2(1.0), 1u, _GLF_struct_26(_GLF_struct_23(mat3x4(1.0), ivec3(1)), _GLF_struct_24(mat4x3(1.0), ivec2(1), ivec4(1), vec3(1.0)), ivec3(1), _GLF_struct_25(ivec3(1), gl_WorkGroupID.x, mat2(1.0))));
 GLF_merged4_0_1_16_1_1_13_2_1_6_3_1_12next_virtual_gidnum_workgroupread_1workgroup_id.w = _GLF_struct_replacement_27._f2._f3.workgroup_id;
 uint workgroup_base = workgroup_size * GLF_merged4_0_1_16_1_1_13_2_1_6_3_1_12next_virtual_gidnum_workgroupread_1workgroup_id.w;
 _GLF_struct_17 _GLF_struct_replacement_17 = _GLF_struct_17(uvec2(1u), _GLF_struct_12(_GLF_struct_8(uvec4(1u), vec3(1.0)), bvec2(true), _GLF_struct_9(bvec2(true), mat3(1.0)), mat2x4(1.0), _GLF_struct_10(uvec4(1u), uvec3(1u), mat2x3(1.0), uvec3(1u)), _GLF_struct_11(vec3(1.0), uvec2(1u), uvec2(1u), uvec4(1u)), true), bvec4(true), _GLF_struct_16(_GLF_struct_13(ivec4(1), mat4(1.0), mat3x4(1.0), vec4(1.0), uvec4(1u), bvec2(true), mat3(1.0)), uvec3(1u), mat4x2(1.0), _GLF_struct_14(bvec3(true), uvec3(1u), uvec4(1u), 1.0, ivec3(1), ivec4(1), bvec4(true)), 1.0, _GLF_struct_15(1, uvec3(1u), ivec2(1), uvec2(1u), mat3x2(1.0)), bvec4(true)), workgroup_base + _GLF_struct_replacement_7.subgroup_id * _GLF_struct_replacement_22._f0._f2.subgroup_size + subgroup_local_id, true);
 uint next_virtual_gid = workgroup_base + _GLF_struct_replacement_7.subgroup_id * _GLF_struct_replacement_22._f0._f2.subgroup_size + ((subgroup_local_id + 1) % _GLF_struct_replacement_22._f0._f2.subgroup_size);
 GLF_merged4_0_1_16_1_1_13_2_1_6_3_1_12next_virtual_gidnum_workgroupread_1workgroup_id.x = next_virtual_gid;
 atomicStore(buf[GLF_merged4_0_1_16_1_1_13_2_1_6_3_1_12next_virtual_gidnum_workgroupread_1workgroup_id.x], uint(1), 4, 64, 4);
 uint read_1 = atomicLoad(buf[_GLF_struct_replacement_17.virtual_gid], 4, 64, 0);
 GLF_merged4_0_1_16_1_1_13_2_1_6_3_1_12next_virtual_gidnum_workgroupread_1workgroup_id.z = read_1;
 uint read_2 = atomicLoad(buf[_GLF_struct_replacement_17.virtual_gid], 4, 64, 0);
 atomicStore(buf[GLF_merged4_0_1_16_1_1_13_2_1_6_3_1_12next_virtual_gidnum_workgroupread_1workgroup_id.x], uint(GLF_merged4_0_1_16_1_1_13_2_1_6_3_1_12next_virtual_gidnum_workgroupread_1workgroup_id.z == read_2) + 1, 4, 64, 4);
}
