#version 460
struct _GLF_struct_5 {
 bool _f0;
 mat3x2 _f1;
} ;

struct _GLF_struct_6 {
 _GLF_struct_5 _f0;
 mat2x4 _f1;
 bvec3 _f2;
} ;

struct _GLF_struct_3 {
 vec3 _f0;
 vec4 _f1;
 mat3x2 _f2;
 mat3 _f3;
} ;

struct _GLF_struct_4 {
 bvec2 _f0;
 _GLF_struct_3 _f1;
} ;

struct _GLF_struct_1 {
 uvec3 _f0;
 uvec3 _f1;
 mat4 _f2;
 mat4x3 _f3;
 vec2 _f4;
} ;

struct _GLF_struct_0 {
 bvec3 _f0;
} ;

struct _GLF_struct_2 {
 ivec2 _f0;
 ivec3 _f1;
 _GLF_struct_0 _f2;
 _GLF_struct_1 _f3;
} ;

struct _GLF_struct_7 {
 uint read_1;
 mat3x2 _f0;
 _GLF_struct_2 _f1;
 float _f2;
 mat3 _f3;
 _GLF_struct_4 _f4;
 _GLF_struct_6 _f5;
 mat4 _f6;
} ;

layout(set = 0, binding = 1) uniform buf1 {
 vec2 injectionSwitch;
};
#extension GL_KHR_shader_subgroup_ballot : enable
#extension GL_KHR_shader_subgroup_vote : enable
#extension GL_KHR_shader_subgroup_basic : enable
#extension GL_KHR_memory_scope_semantics : enable
layout(set = 0, binding = 0) buffer Buf {
 uint buf[];
};
layout(local_size_x = 128, local_size_y = 1, local_size_z = 1) in;
void main()
{
 uvec3 GLF_merged3_0_1_16_1_1_13_2_1_14next_virtual_gidnum_workgroupworkgroup_base;
 uvec2 GLF_merged2_0_1_6_1_1_17read_2subgroup_local_id;
 uint subgroup_id = gl_SubgroupID;
uint subgroup_size = 16;
 uint subgroup_local_id = gl_SubgroupInvocationID;
 GLF_merged2_0_1_6_1_1_17read_2subgroup_local_id.y = subgroup_local_id;
 uint num_workgroup = gl_NumWorkGroups.x;
 GLF_merged3_0_1_16_1_1_13_2_1_14next_virtual_gidnum_workgroupworkgroup_base.y = num_workgroup;
 uint workgroup_size = gl_WorkGroupSize.x;
 uint workgroup_id = gl_WorkGroupID.x;
 uint workgroup_base = workgroup_size * workgroup_id;
 GLF_merged3_0_1_16_1_1_13_2_1_14next_virtual_gidnum_workgroupworkgroup_base.z = workgroup_base;
 uint virtual_gid = GLF_merged3_0_1_16_1_1_13_2_1_14next_virtual_gidnum_workgroupworkgroup_base.z + subgroup_id * subgroup_size + GLF_merged2_0_1_6_1_1_17read_2subgroup_local_id.y;
 uint next_virtual_gid = GLF_merged3_0_1_16_1_1_13_2_1_14next_virtual_gidnum_workgroupworkgroup_base.z + subgroup_id * subgroup_size + ((GLF_merged2_0_1_6_1_1_17read_2subgroup_local_id.y + 1) % subgroup_size);
 GLF_merged3_0_1_16_1_1_13_2_1_14next_virtual_gidnum_workgroupworkgroup_base.x = next_virtual_gid;
 atomicStore(buf[GLF_merged3_0_1_16_1_1_13_2_1_14next_virtual_gidnum_workgroupworkgroup_base.x], uint(1), 4, 64, 4);
 _GLF_struct_7 _GLF_struct_replacement_7 = _GLF_struct_7(atomicLoad(buf[virtual_gid], 4, 64, 0), mat3x2(1.0), _GLF_struct_2(ivec2(1), ivec3(1), _GLF_struct_0(bvec3(true)), _GLF_struct_1(uvec3(1u), uvec3(1u), mat4(1.0), mat4x3(1.0), vec2(1.0))), 1.0, mat3(1.0), _GLF_struct_4(bvec2(true), _GLF_struct_3(vec3(1.0), vec4(1.0), mat3x2(1.0), mat3(1.0))), _GLF_struct_6(_GLF_struct_5(true, mat3x2(1.0)), mat2x4(1.0), bvec3(true)), mat4(1.0));
 uint read_2 = atomicLoad(buf[virtual_gid], 4, 64, 0);
 GLF_merged2_0_1_6_1_1_17read_2subgroup_local_id.x = read_2;
 if(GLF_merged2_0_1_6_1_1_17read_2subgroup_local_id.y + 1 < subgroup_size)
  {
   atomicStore(buf[GLF_merged3_0_1_16_1_1_13_2_1_14next_virtual_gidnum_workgroupworkgroup_base.x], uint(_GLF_struct_replacement_7.read_1 == GLF_merged2_0_1_6_1_1_17read_2subgroup_local_id.x) + 1, 4, 64, 4);
   subgroupAll(false);
  }
 else
  {
   atomicStore(buf[GLF_merged3_0_1_16_1_1_13_2_1_14next_virtual_gidnum_workgroupworkgroup_base.x], uint(_GLF_struct_replacement_7.read_1 == GLF_merged2_0_1_6_1_1_17read_2subgroup_local_id.x) + 1, 4, 64, 4);
   subgroupAll(true);
  }
}
