#version 460

#ifndef REDUCER
#define _GLF_ZERO(X, Y)                   (Y)
#define _GLF_ONE(X, Y)                    (Y)
#define _GLF_FALSE(X, Y)                  (Y)
#define _GLF_TRUE(X, Y)                   (Y)
#define _GLF_IDENTITY(X, Y)               (Y)
#define _GLF_DEAD(X)                      (X)
#define _GLF_FUZZED(X)                    (X)
#define _GLF_WRAPPED_LOOP(X)              X
#define _GLF_WRAPPED_IF_TRUE(X)           X
#define _GLF_WRAPPED_IF_FALSE(X)          X
#define _GLF_SWITCH(X)                    X
#define _GLF_MAKE_IN_BOUNDS_INT(IDX, SZ)  clamp(IDX, 0, SZ - 1)
#define _GLF_MAKE_IN_BOUNDS_UINT(IDX, SZ) clamp(IDX, 0u, SZ - 1u)
#endif


layout(set = 0, binding = 1) uniform buf1 {
 vec2 injectionSwitch;
};
#extension GL_KHR_shader_subgroup_vote : enable
#extension GL_KHR_shader_subgroup_basic : enable
#extension GL_KHR_memory_scope_semantics : enable
#extension GL_EXT_maximal_reconvergence : enable
layout(set = 0, binding = 0) buffer Buf {
 uint buf[];
};
layout(set = 0, binding = 2) buffer Checker {
 uint checker[];
};
layout(local_size_x = 128, local_size_y = 1, local_size_z = 1) in;
void main()
{
 uvec4 GLF_merged3_0_2_53_2_1_4_3_1_13GLF_merged2_0_1_14_1_1_14workgroup_baseworkgroup_sizereadsubgroup_base;
 uvec2 GLF_merged2_0_1_14_1_1_14workgroup_baseworkgroup_size;
 GLF_merged3_0_2_53_2_1_4_3_1_13GLF_merged2_0_1_14_1_1_14workgroup_baseworkgroup_sizereadsubgroup_base.xy = GLF_merged2_0_1_14_1_1_14workgroup_baseworkgroup_size;
 uvec4 GLF_merged4_0_1_4_1_1_11_2_1_17_3_1_12readsubgroup_idsubgroup_local_idworkgroup_id;
 uvec4 GLF_merged4_0_1_17_1_1_13_2_1_11_3_1_14subgroup_local_idsubgroup_sizevirtual_gidworkgroup_size;
 uint subgroup_id = gl_SubgroupID;
 GLF_merged4_0_1_4_1_1_11_2_1_17_3_1_12readsubgroup_idsubgroup_local_idworkgroup_id.y = subgroup_id;
 uint subgroup_size = gl_SubgroupSize;
 GLF_merged4_0_1_17_1_1_13_2_1_11_3_1_14subgroup_local_idsubgroup_sizevirtual_gidworkgroup_size.y = subgroup_size;
 if(_GLF_DEAD(false))
  return;
 uint subgroup_local_id = gl_SubgroupInvocationID;
 GLF_merged4_0_1_4_1_1_11_2_1_17_3_1_12readsubgroup_idsubgroup_local_idworkgroup_id.z = subgroup_local_id;
 GLF_merged4_0_1_17_1_1_13_2_1_11_3_1_14subgroup_local_idsubgroup_sizevirtual_gidworkgroup_size.x = GLF_merged4_0_1_4_1_1_11_2_1_17_3_1_12readsubgroup_idsubgroup_local_idworkgroup_id.z;
 uint num_workgroup = gl_NumWorkGroups.x;
 uint workgroup_size = gl_WorkGroupSize.x;
 GLF_merged3_0_2_53_2_1_4_3_1_13GLF_merged2_0_1_14_1_1_14workgroup_baseworkgroup_sizereadsubgroup_base.xy.y = workgroup_size;
 GLF_merged4_0_1_17_1_1_13_2_1_11_3_1_14subgroup_local_idsubgroup_sizevirtual_gidworkgroup_size.w = GLF_merged3_0_2_53_2_1_4_3_1_13GLF_merged2_0_1_14_1_1_14workgroup_baseworkgroup_sizereadsubgroup_base.xy.y;
 uint workgroup_id = gl_WorkGroupID.x;
 GLF_merged4_0_1_4_1_1_11_2_1_17_3_1_12readsubgroup_idsubgroup_local_idworkgroup_id.w = workgroup_id;
 uint workgroup_base = GLF_merged4_0_1_17_1_1_13_2_1_11_3_1_14subgroup_local_idsubgroup_sizevirtual_gidworkgroup_size.w * GLF_merged4_0_1_4_1_1_11_2_1_17_3_1_12readsubgroup_idsubgroup_local_idworkgroup_id.w;
 GLF_merged3_0_2_53_2_1_4_3_1_13GLF_merged2_0_1_14_1_1_14workgroup_baseworkgroup_sizereadsubgroup_base.xy.x = workgroup_base;
 uint subgroup_base = GLF_merged4_0_1_4_1_1_11_2_1_17_3_1_12readsubgroup_idsubgroup_local_idworkgroup_id.y * GLF_merged4_0_1_17_1_1_13_2_1_11_3_1_14subgroup_local_idsubgroup_sizevirtual_gidworkgroup_size.y;
 GLF_merged3_0_2_53_2_1_4_3_1_13GLF_merged2_0_1_14_1_1_14workgroup_baseworkgroup_sizereadsubgroup_base.w = subgroup_base;
 uint virtual_gid = GLF_merged3_0_2_53_2_1_4_3_1_13GLF_merged2_0_1_14_1_1_14workgroup_baseworkgroup_sizereadsubgroup_base.xy.x + GLF_merged3_0_2_53_2_1_4_3_1_13GLF_merged2_0_1_14_1_1_14workgroup_baseworkgroup_sizereadsubgroup_base.w + GLF_merged4_0_1_17_1_1_13_2_1_11_3_1_14subgroup_local_idsubgroup_sizevirtual_gidworkgroup_size.x;
 GLF_merged4_0_1_17_1_1_13_2_1_11_3_1_14subgroup_local_idsubgroup_sizevirtual_gidworkgroup_size.z = virtual_gid;
 uint next_virtual_gid = GLF_merged3_0_2_53_2_1_4_3_1_13GLF_merged2_0_1_14_1_1_14workgroup_baseworkgroup_sizereadsubgroup_base.xy.x + GLF_merged3_0_2_53_2_1_4_3_1_13GLF_merged2_0_1_14_1_1_14workgroup_baseworkgroup_sizereadsubgroup_base.w + ((GLF_merged4_0_1_17_1_1_13_2_1_11_3_1_14subgroup_local_idsubgroup_sizevirtual_gidworkgroup_size.x + 1) % GLF_merged4_0_1_17_1_1_13_2_1_11_3_1_14subgroup_local_idsubgroup_sizevirtual_gidworkgroup_size.y);
 uint read = atomicLoad(buf[GLF_merged4_0_1_17_1_1_13_2_1_11_3_1_14subgroup_local_idsubgroup_sizevirtual_gidworkgroup_size.z], 4, 64, 2);
 GLF_merged3_0_2_53_2_1_4_3_1_13GLF_merged2_0_1_14_1_1_14workgroup_baseworkgroup_sizereadsubgroup_base.z = read;
 GLF_merged4_0_1_4_1_1_11_2_1_17_3_1_12readsubgroup_idsubgroup_local_idworkgroup_id.x = GLF_merged3_0_2_53_2_1_4_3_1_13GLF_merged2_0_1_14_1_1_14workgroup_baseworkgroup_sizereadsubgroup_base.z;
 if((GLF_merged4_0_1_17_1_1_13_2_1_11_3_1_14subgroup_local_idsubgroup_sizevirtual_gidworkgroup_size.x % 2) == 0)
  {
   if(_GLF_DEAD(_GLF_FALSE(false, (injectionSwitch.x > injectionSwitch.y))))
    return;
   atomicStore(buf[next_virtual_gid], uint(1), 4, 64, 4);
  }
 else
  {
   atomicStore(buf[next_virtual_gid], uint(1), 4, 64, 4);
  }
 subgroupBarrier();
 atomicStore(checker[GLF_merged4_0_1_17_1_1_13_2_1_11_3_1_14subgroup_local_idsubgroup_sizevirtual_gidworkgroup_size.z], GLF_merged4_0_1_4_1_1_11_2_1_17_3_1_12readsubgroup_idsubgroup_local_idworkgroup_id.x, 4, 64, 4);
 if(_GLF_DEAD(_GLF_FALSE(false, (injectionSwitch.x > injectionSwitch.y))))
  return;
}
