#version 460
struct _GLF_struct_8 {
 bvec3 _f0;
 uvec4 _f1;
 ivec4 _f2;
 vec3 _f3;
} ;

struct _GLF_struct_9 {
 _GLF_struct_8 _f0;
 vec2 _f1;
} ;

struct _GLF_struct_6 {
 uvec2 _f0;
} ;

struct _GLF_struct_7 {
 _GLF_struct_6 _f0;
} ;

struct _GLF_struct_4 {
 mat4 _f0;
 vec2 _f1;
 vec3 _f2;
 uint _f3;
 uint workgroup_size;
 mat3x4 _f4;
 ivec4 _f5;
 mat4x3 _f6;
} ;

struct _GLF_struct_3 {
 uvec4 _f0;
} ;

struct _GLF_struct_5 {
 _GLF_struct_3 _f0;
 _GLF_struct_4 _f1;
 mat3x4 _f2;
 vec3 _f3;
 mat2x4 _f4;
 bvec2 _f5;
} ;

struct _GLF_struct_1 {
 mat4 _f0;
 mat2x3 _f1;
} ;

struct _GLF_struct_0 {
 bvec4 _f0;
 mat4 _f1;
 ivec3 _f2;
 float _f3;
} ;

struct _GLF_struct_2 {
 _GLF_struct_0 _f0;
 _GLF_struct_1 _f1;
 uvec3 _f2;
 mat2x4 _f3;
 mat2 _f4;
} ;

struct _GLF_struct_10 {
 _GLF_struct_2 _f0;
 _GLF_struct_5 _f1;
 _GLF_struct_7 _f2;
 _GLF_struct_9 _f3;
 vec3 _f4;
} ;

layout(set = 0, binding = 1) uniform buf1 {
 vec2 injectionSwitch;
};
#extension GL_KHR_shader_subgroup_ballot : enable
#extension GL_KHR_shader_subgroup_vote : enable
#extension GL_KHR_shader_subgroup_basic : enable
#extension GL_KHR_memory_scope_semantics : enable
layout(set = 0, binding = 0) buffer Buf {
 uint buf[];
};
layout(set = 0, binding = 2) buffer WriteVal {
 uint write_val;
};
layout(local_size_x = 128, local_size_y = 1, local_size_z = 1) in;
void main()
{
 uvec4 GLF_merged4_0_1_8_1_1_11_2_1_13_3_1_12read_valsubgroup_idsubgroup_sizeworkgroup_id;
 uvec2 GLF_merged2_0_1_11_1_1_12virtual_gidworkgroup_id;
 uvec2 GLF_merged2_0_1_8_1_1_13read_valsubgroup_size;
 uvec4 GLF_merged4_0_1_13_1_1_11_2_1_17_3_1_11num_workgroupsubgroup_idsubgroup_local_idvirtual_gid;
 uint subgroup_id = gl_SubgroupID;
 GLF_merged4_0_1_8_1_1_11_2_1_13_3_1_12read_valsubgroup_idsubgroup_sizeworkgroup_id.y = subgroup_id;
 GLF_merged4_0_1_13_1_1_11_2_1_17_3_1_11num_workgroupsubgroup_idsubgroup_local_idvirtual_gid.y = GLF_merged4_0_1_8_1_1_11_2_1_13_3_1_12read_valsubgroup_idsubgroup_sizeworkgroup_id.y;
 uint subgroup_size = gl_SubgroupSize;
 GLF_merged4_0_1_8_1_1_11_2_1_13_3_1_12read_valsubgroup_idsubgroup_sizeworkgroup_id.z = subgroup_size;
 GLF_merged2_0_1_8_1_1_13read_valsubgroup_size.y = GLF_merged4_0_1_8_1_1_11_2_1_13_3_1_12read_valsubgroup_idsubgroup_sizeworkgroup_id.z;
 uint subgroup_local_id = gl_SubgroupInvocationID;
 GLF_merged4_0_1_13_1_1_11_2_1_17_3_1_11num_workgroupsubgroup_idsubgroup_local_idvirtual_gid.z = subgroup_local_id;
 uint num_workgroup = gl_NumWorkGroups.x;
 GLF_merged4_0_1_13_1_1_11_2_1_17_3_1_11num_workgroupsubgroup_idsubgroup_local_idvirtual_gid.x = num_workgroup;
 _GLF_struct_10 _GLF_struct_replacement_10 = _GLF_struct_10(_GLF_struct_2(_GLF_struct_0(bvec4(true), mat4(1.0), ivec3(1), 1.0), _GLF_struct_1(mat4(1.0), mat2x3(1.0)), uvec3(1u), mat2x4(1.0), mat2(1.0)), _GLF_struct_5(_GLF_struct_3(uvec4(1u)), _GLF_struct_4(mat4(1.0), vec2(1.0), vec3(1.0), 1u, gl_WorkGroupSize.x, mat3x4(1.0), ivec4(1), mat4x3(1.0)), mat3x4(1.0), vec3(1.0), mat2x4(1.0), bvec2(true)), _GLF_struct_7(_GLF_struct_6(uvec2(1u))), _GLF_struct_9(_GLF_struct_8(bvec3(true), uvec4(1u), ivec4(1), vec3(1.0)), vec2(1.0)), vec3(1.0));
 uint workgroup_id = gl_WorkGroupID.x;
 GLF_merged4_0_1_8_1_1_11_2_1_13_3_1_12read_valsubgroup_idsubgroup_sizeworkgroup_id.w = workgroup_id;
 GLF_merged2_0_1_11_1_1_12virtual_gidworkgroup_id.y = GLF_merged4_0_1_8_1_1_11_2_1_13_3_1_12read_valsubgroup_idsubgroup_sizeworkgroup_id.w;
 uint workgroup_base = _GLF_struct_replacement_10._f1._f1.workgroup_size * GLF_merged2_0_1_11_1_1_12virtual_gidworkgroup_id.y;
 uint virtual_gid = workgroup_base + GLF_merged4_0_1_13_1_1_11_2_1_17_3_1_11num_workgroupsubgroup_idsubgroup_local_idvirtual_gid.y * GLF_merged2_0_1_8_1_1_13read_valsubgroup_size.y + GLF_merged4_0_1_13_1_1_11_2_1_17_3_1_11num_workgroupsubgroup_idsubgroup_local_idvirtual_gid.z;
 GLF_merged2_0_1_11_1_1_12virtual_gidworkgroup_id.x = virtual_gid;
 GLF_merged4_0_1_13_1_1_11_2_1_17_3_1_11num_workgroupsubgroup_idsubgroup_local_idvirtual_gid.w = GLF_merged2_0_1_11_1_1_12virtual_gidworkgroup_id.x;
 atomicStore(write_val, uint(GLF_merged4_0_1_13_1_1_11_2_1_17_3_1_11num_workgroupsubgroup_idsubgroup_local_idvirtual_gid.w), 4, 64, 0);
 uint read_val = atomicLoad(write_val, 4, 64, 0);
 GLF_merged4_0_1_8_1_1_11_2_1_13_3_1_12read_valsubgroup_idsubgroup_sizeworkgroup_id.x = read_val;
 GLF_merged2_0_1_8_1_1_13read_valsubgroup_size.x = GLF_merged4_0_1_8_1_1_11_2_1_13_3_1_12read_valsubgroup_idsubgroup_sizeworkgroup_id.x;
 buf[GLF_merged4_0_1_13_1_1_11_2_1_17_3_1_11num_workgroupsubgroup_idsubgroup_local_idvirtual_gid.w] = uint(subgroupAllEqual(GLF_merged2_0_1_8_1_1_13read_valsubgroup_size.x));
}
