#version 460
layout(set = 0, binding = 1) uniform buf1 {
 vec2 injectionSwitch;
};
#extension GL_KHR_shader_subgroup_ballot : enable
#extension GL_KHR_shader_subgroup_vote : enable
#extension GL_KHR_shader_subgroup_basic : enable
#extension GL_KHR_memory_scope_semantics : enable
layout(set = 0, binding = 0) buffer Buf {
 uint buf[];
};
layout(set = 0, binding = 2) buffer Checker {
 uint checker[];
};
layout(local_size_x = 128, local_size_y = 1, local_size_z = 1) in;
void main()
{
 uvec4 GLF_merged4_0_1_4_1_1_13_2_1_12_3_1_14readsubgroup_sizeworkgroup_idworkgroup_size;
 uvec2 GLF_merged2_0_1_4_1_1_11readvirtual_gid;
 uint subgroup_id = gl_SubgroupID;
 uint subgroup_size = gl_SubgroupSize;
 GLF_merged4_0_1_4_1_1_13_2_1_12_3_1_14readsubgroup_sizeworkgroup_idworkgroup_size.y = subgroup_size;
 uint subgroup_local_id = gl_SubgroupInvocationID;
 uint num_workgroup = gl_NumWorkGroups.x;
 uint workgroup_size = gl_WorkGroupSize.x;
 GLF_merged4_0_1_4_1_1_13_2_1_12_3_1_14readsubgroup_sizeworkgroup_idworkgroup_size.w = workgroup_size;
 uint workgroup_id = gl_WorkGroupID.x;
 GLF_merged4_0_1_4_1_1_13_2_1_12_3_1_14readsubgroup_sizeworkgroup_idworkgroup_size.z = workgroup_id;
 uint workgroup_base = GLF_merged4_0_1_4_1_1_13_2_1_12_3_1_14readsubgroup_sizeworkgroup_idworkgroup_size.w * GLF_merged4_0_1_4_1_1_13_2_1_12_3_1_14readsubgroup_sizeworkgroup_idworkgroup_size.z;
 uint virtual_gid = workgroup_base + subgroup_id * GLF_merged4_0_1_4_1_1_13_2_1_12_3_1_14readsubgroup_sizeworkgroup_idworkgroup_size.y + subgroup_local_id;
 GLF_merged2_0_1_4_1_1_11readvirtual_gid.y = virtual_gid;
 uint next_virtual_gid = workgroup_base + subgroup_id * GLF_merged4_0_1_4_1_1_13_2_1_12_3_1_14readsubgroup_sizeworkgroup_idworkgroup_size.y + ((subgroup_local_id + 1) % GLF_merged4_0_1_4_1_1_13_2_1_12_3_1_14readsubgroup_sizeworkgroup_idworkgroup_size.y);
 uint read = atomicLoad(buf[GLF_merged2_0_1_4_1_1_11readvirtual_gid.y], 4, 64, 0);
 GLF_merged4_0_1_4_1_1_13_2_1_12_3_1_14readsubgroup_sizeworkgroup_idworkgroup_size.x = read;
 GLF_merged2_0_1_4_1_1_11readvirtual_gid.x = GLF_merged4_0_1_4_1_1_13_2_1_12_3_1_14readsubgroup_sizeworkgroup_idworkgroup_size.x;
 atomicStore(buf[next_virtual_gid], uint(1), 4, 64, 4);
 if(subgroup_local_id + 1 < GLF_merged4_0_1_4_1_1_13_2_1_12_3_1_14readsubgroup_sizeworkgroup_idworkgroup_size.y)
  {
   atomicStore(checker[GLF_merged2_0_1_4_1_1_11readvirtual_gid.y], GLF_merged2_0_1_4_1_1_11readvirtual_gid.x, 4, 64, 4);
   subgroupAll(false);
  }
 else
  {
   atomicStore(buf[GLF_merged2_0_1_4_1_1_11readvirtual_gid.y], GLF_merged2_0_1_4_1_1_11readvirtual_gid.x, 4, 64, 4);
   subgroupAll(true);
  }
}
